
language: python
python: 3.8

branches:
  only:
    - master

jobs:
  include:
    - if: commit_message !~ /\[deploy\]/
      # run all tests
      script:
        - echo 0

      # after a successful test, update to codecov
      after_success:
        - bash <(curl -s https://codecov.io/bash)
        - |
          version=$(python _scripts/increment_version.py)
#          cd docs
#          make html
#          cd ..
          git config user.name "doclockh"
          git config user.email "chris@lockhartlab.org"
          git checkout master
          git add -A
          git commit -m "[deploy] ${TRAVIS_COMMIT_MESSAGE}"
          git tag $version
          git push -fq https://doclockh:"${GIT_API_KEY}"@github.com/"${TRAVIS_REPO_SLUG}".git master:master --tags

    - if: commit_message =~ /\[deploy\]/
      #
      script:
        - echo 0

      # deploy to pyp
      deploy:
        - provider: pypi
          user: "__token__"
          password:
            secure: rJSvuQNi2Dc/kHhY31JhOQFQTMFFn9cH14OtznwkkrBDmjCaZAKf7LGXhGTsnWKkzgNLYLvqyiuxA7/NKJyOpEdbHrZ34yFIyp/QEQurjYff45kR+l0RTl6bBL8Fa3yUFIPROnFvZAtebW2+9c4kdgAslDXifPNzq0CTUJ50lHEXH/FCJ2Or2dam3hLda13WujJHUJht96G3vvIz5/VVE47R68pdwar5BfVMHKM3dfgH0uWEgsfTqHsN6W9FM6aCiaitPORCwEXwJgeb3qJwze4lP+ualnGMizLKgODqyTRwc0t+3/uOkhuQ05lyFixPs0gCEojcNPp8i47yVLriq071+8Jdq/AIzvRMf5XaOS6WB3ay2zhFfSEPdHs9JAET8rMIZEFpboIPCxIA3e1i4VDd3Ss0YyLr2tGBSENlXhLb7HDiFODF6oNOXIYx9T84Gj03YM4k1uba/Y/ADz5a3mQU115uHdqIr0oAk6FVuBPnKKfj2FWYl2KFPG9Zse5ihgLYmhZEzbXLBLGYRnJjzn+nBpjzrbjzQ6VPwxkcEzc9zVm8JO9TPdLxAc94mvdasUaFEv7W046VDghnWZgtrmbN6rzGU8qpXOKJbHP0MW6Yx8YvcEa8ELeKaTBORSbyGD/CNJixZY8szyC/D6poiU65eIDjBnCyZF7z5pvsKts=
          twine_check: true
          skip_cleanup: true
#          on:
#            tags: true

notifications:
  email:
    on_success: never
    on_failure: always